### ISSUE TITLE
Change switching view keyboard shortcuts to something less conflicted

### ISSUE THREAD

**Issue by ericallam** [apihero-run/jsonhero-web#94]
They are currently set to `cmd+1`, `cmd+2`, `cmd+3`, which overrides many browsers own command shortcuts.

**Comment by ckifer** [comment]
I can take this. 

I like the numbers (1, 2, 3)... it makes sense to me to keep with that theme. Do we think `cmd`/`ctrl`+`shift`+{number} is too much to press? All other common key combos risk browser shortcut conflicts. Since `shift` + `c` is already the shortcut for copy does `shift + {number}` make sense? All of these shortcuts have risks if jsonhero supports editing.

**Comment by ericallam** [comment]
Yea I was thinking cmd+shift+(number) should be okay, but would be good to research if that also conflicts with built in browser and OS shortcuts

**Comment by ckifer** [comment]
Sounds good. I totally forgot, cmd+shift+3,4 on Mac are screenshot shortcuts. That won't do. Otherwise it only conflicts with Opera. 

Will do some more research, I found a few good resources that need looked through.

**Comment by ckifer** [comment]
Looking through https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts for OS shortcuts, [chrome shortcuts](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Ctab-window-shortcuts%2Cgoogle-chrome-feature-shortcuts), and FF shortcuts.

Out of everything I think `alt + n` for Windows/Linux and `control + n` on Mac works out the best. Anything is better than `cmd/ctrl` because that is an explicit, well known browser shortcut to change to tab `n`. `shift+n` is more likely to be pressed for trying to type special characters, and `cmd+shift+n` results in screenshots on Mac.

`control+n` types less used special characters on Mac (¡™£¢¢∞§). I will have to double check what the shortcut it on Windows but I think its suitable for JSON hero unless there are objections.

**Comment by ericallam** [comment]
Yea that sounds good!
